### ISSUE TITLE
Serverless deployment example

### ISSUE THREAD

**Issue by jlarmstrongiv** [kingoflolz/mesh-transformer-jax#33]
Found you on [ProductHunt](https://www.producthunt.com/posts/gpt-j) today! 🎉 I’m very impressed by your work and enjoyed reading the blog posts.  

I think there’s a great opportunity for a one-command-deploy api via serverless (`serverless deploy`).  I think this option will make your work very accessible to hobbyists (easy deployment, low cost, low maintenance, scalable).

AWS recently released [support](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html) for docker lambda functions, which the serverless framework now [supports](https://www.serverless.com/blog/container-support-for-lambda) too.

Luckily, the serverless limit with docker is 10GB, so the 8.8GB slim weights for inference should fit snuggly.  

The serverless.yml file could look like:
```yml
service: gpt-j
frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: python:3.8
  memorySize: 10240
    ecr:
    images:
      gpt-j:
        path: ./
        file: ./Dockerfile
functions:
  gpt-j:
    image:
      name: gpt-j
    events:
      - httpApi:
          method: post
          path: /predict
```

The dockerfile would look similar to your existing Dockerfile, but use the AWS runtime:
```dockerfile
FROM public.ecr.aws/lambda/python:3.8

# install gpt-j
# app.py handles inference

COPY app.py   ./
CMD ["app.handler"]      
```
There would only be a single api call, since a lambda services only a single request at a time.

I wish I could be of more help, but my specialty at the moment is JavaScript, not Python.  I will gladly test any demos though 😄 already having a Dockerfile example means half the work is probably done
